/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Controlador.Controlador;
import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import methods.*;
import hilos.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import Paneles.*;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author JORGE DELGADILLO
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
      //instanciamo la clase para el cambio de tamaño 
    cambioTamaño cambio = new cambioTamaño();
    //instanciomos la clase para hacer el cambio de los paneles para navegar
    cambioPaneles cambioPanel = new cambioPaneles();
    //instanciamos la clase para el reloj y la fecha
    reloj_fecha reloj = new reloj_fecha();

    int x,y;
    
    botones boton = new botones();

    
    private Controlador controlador;
    private login login;
    private String correo;
    private String tipo;
    public Administrador(){
         this.correo = "";
         this.tipo = "administrador";
         this.controlador = null;
      
            initComponents();
            //ubicamos al centro de la pantalla
            setLocationRelativeTo(null);
            //ponemos un icono en el label para el fondo de pantalla
            lbFondo.setIcon(cambio.cambio(1240,720,"/img/fondo.png"));
            //hacemos el borde redondo
            Shape form = new RoundRectangle2D.Double(0,0,this.getBounds().width,this.getBounds().height,27,27);
            
            AWTUtilities.setWindowShape(this,form);
            //colocamos la hora
            reloj.iniciar(lbHora, lbFecha);
            //metodo para hacer qeu el fondo se vea
            
            lbPerfilUsuario.setIcon(cambio.cambio(150, 150, "/img/person.png"));
            //para el paneln d3l perfil
            
            panelPerfilDos.setBackground(Color.red);
            
            
            
    }
    void setInicio() throws SQLException{
            cambioPanel.cambiar_panel("inicio",panelPrincipal,799,449,correo,tipo,controlador);
    }
    void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    void setLogin(login login) {
        this.login = login;
    }

    void setDatos(String[] datos,ImageIcon imagen) {
        
        lbUsuario.setText(datos[0]);
        lbNombre.setText(datos[1]);
        lbApellidos.setText(datos[2]);
        
        lbPerfilUsuario.setIcon(imagen);
        
    }
    void setCorreo(String correo){
        this.correo = correo;
        
    }
    
    //metodo que permite cambiar el icono de la plataformaen la barar de tareas de windows
     public Image getIconImage(){       
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/info_sistemas.png"));       
        return retvalue;  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomHora = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        lbNomfecha = new javax.swing.JLabel();
        panelPerfilDos = new javax.swing.JPanel();
        lbPerfilUsuario = new javax.swing.JLabel();
        lbNomEmail = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbNomNombres = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbNomApellidos = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();
        lbFecha = new javax.swing.JLabel();
        umss = new javax.swing.JLabel();
        laboNombre = new javax.swing.JLabel();
        pEstudiante = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        lbTiposCursos = new javax.swing.JLabel();
        btnCursoCreado = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        btnChat = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEstudiantes = new javax.swing.JButton();
        btnEducador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnConfig = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNomHora.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbNomHora.setForeground(new java.awt.Color(255, 255, 255));
        lbNomHora.setText("Hora:");
        getContentPane().add(lbNomHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lbHora.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 100, 20));

        lbNomfecha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbNomfecha.setForeground(new java.awt.Color(255, 255, 255));
        lbNomfecha.setText("Fecha :");
        getContentPane().add(lbNomfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        panelPerfilDos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil del Usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lbNomEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNomEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbNomEmail.setText("Usuario :");

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbNomNombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNomNombres.setForeground(new java.awt.Color(255, 255, 255));
        lbNomNombres.setText("Nombres :");

        lbNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbNomApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNomApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lbNomApellidos.setText("Apellidos :");

        lbApellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lbApellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnInfo.setBackground(new java.awt.Color(204, 204, 255));
        btnInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInfo.setText("Editar Informacion");
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInfoMouseExited(evt);
            }
        });
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPerfilDosLayout = new javax.swing.GroupLayout(panelPerfilDos);
        panelPerfilDos.setLayout(panelPerfilDosLayout);
        panelPerfilDosLayout.setHorizontalGroup(
            panelPerfilDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilDosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPerfilDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPerfilDosLayout.createSequentialGroup()
                        .addComponent(lbApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(panelPerfilDosLayout.createSequentialGroup()
                .addGroup(panelPerfilDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPerfilDosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNomNombres))
                    .addGroup(panelPerfilDosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNomEmail))
                    .addGroup(panelPerfilDosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerfilDosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNomApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerfilDosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(btnInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPerfilDosLayout.setVerticalGroup(
            panelPerfilDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilDosLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lbPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(lbNomEmail)
                .addGap(18, 18, 18)
                .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNomNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNomApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnInfo)
                .addContainerGap())
        );

        getContentPane().add(panelPerfilDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, 540));

        lbFecha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, 20));

        umss.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        umss.setText("\" Universidad Mayor de San Simón \"");
        getContentPane().add(umss, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        laboNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laboNombre.setText("Laboratorios de Informática Sistemas");
        getContentPane().add(laboNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        pEstudiante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pEstudiante.setText("PLATAFORMA DEL ADMINISTRADOR");
        getContentPane().add(pEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorderPainted(false);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 100, 60));

        btnInicio.setBackground(new java.awt.Color(204, 204, 255));
        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 120, 80));

        lbTiposCursos.setText("Cursos:");
        getContentPane().add(lbTiposCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        btnCursoCreado.setBackground(new java.awt.Color(204, 204, 255));
        btnCursoCreado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCursoCreado.setText("Creados");
        btnCursoCreado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCursoCreadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCursoCreadoMouseExited(evt);
            }
        });
        btnCursoCreado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoCreadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCursoCreado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 120, -1));

        btnCursos.setBackground(new java.awt.Color(204, 204, 255));
        btnCursos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCursos.setText("Todos");
        btnCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCursosMouseExited(evt);
            }
        });
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 120, -1));

        btnChat.setBackground(new java.awt.Color(204, 204, 255));
        btnChat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnChat.setText("Mensajes");
        btnChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChatMouseExited(evt);
            }
        });
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });
        getContentPane().add(btnChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 120, 80));

        panelPrincipal.setOpaque(false);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 780, 520));

        jLabel1.setText("Usuarios:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        btnEstudiantes.setBackground(new java.awt.Color(204, 204, 255));
        btnEstudiantes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEstudiantes.setText("Estudiantes");
        btnEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstudiantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstudiantesMouseExited(evt);
            }
        });
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 120, -1));

        btnEducador.setBackground(new java.awt.Color(204, 204, 255));
        btnEducador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEducador.setText("Profesor");
        btnEducador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEducadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEducadorMouseExited(evt);
            }
        });
        btnEducador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEducadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnEducador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 120, -1));

        jLabel2.setText("Configuraciones:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 100, -1));

        btnConfig.setBackground(new java.awt.Color(204, 204, 255));
        btnConfig.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConfig.setText("Configuración");
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfigMouseExited(evt);
            }
        });
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 120, -1));

        btnAdmin.setBackground(new java.awt.Color(204, 204, 255));
        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdmin.setText("Aministradores");
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminMouseExited(evt);
            }
        });
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        lbFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbFondoMouseDragged(evt);
            }
        });
        lbFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbFondoMousePressed(evt);
            }
        });
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 1230, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFondoMouseDragged
        // movimiento de la ventana en la pantalla
        //capturamos la posicion del mause al moverlo
        Point p = MouseInfo.getPointerInfo().getLocation();
        //movemos el frame en la direccion en la que arrastremos el mouse
        setLocation(p.x-x,p.y-y);
    }//GEN-LAST:event_lbFondoMouseDragged

    private void lbFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFondoMousePressed
        // mivimiento de la pantalla en la panatalla
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lbFondoMousePressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        login.eliminarContraseña();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        try {
            // cambiamos al panel inicio
            cambioPanel.cambiar_panel("inicio",panelPrincipal,799,449,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCursoCreadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoCreadoActionPerformed
        try {
            // TODO add your handling code here:
            cambioPanel.cambiar_panel("misCursos",panelPrincipal,799,449,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCursoCreadoActionPerformed

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed

        try {
            // cambiamos al panel de todos los cursos
            cambioPanel.cambiar_panel("cursos",panelPrincipal,799,499,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        try {
            // cambiamos al panel mensajes
            cambioPanel.cambiar_panel("mensajes",panelPrincipal,799,449,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChatActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
          //cuando se activa la ventana administrador
          setDatos(controlador.getDatosUsuario(correo),controlador.getImagenPerfil(correo));
    }//GEN-LAST:event_formWindowActivated

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        try {
            // cambiamos al panel de estudiantes
            cambioPanel.cambiar_panel("estudiantes",panelPrincipal,799,449,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnEducadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEducadorActionPerformed
        try {
            // cambiamos los profesores o tutores totales
            cambioPanel.cambiar_panel("profesores",panelPrincipal,799,449,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEducadorActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        try {
            // cambiamos al panel de los administradores
            cambioPanel.cambiar_panel("administradores",panelPrincipal,799,449,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        try {
            // cambiamos a el panel de las configuraciones
            cambioPanel.cambiar_panel("config",panelPrincipal,799,449,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        boton.cambioColorSalir(btnSalir, "entrada");
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        boton.cambioColorSalir(btnSalir, "salida");
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnInicio, "entrada");
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnInicio, "salida");
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnEstudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnEstudiantes, "entrada");
    }//GEN-LAST:event_btnEstudiantesMouseEntered

    private void btnEstudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnEstudiantes, "salida");
    }//GEN-LAST:event_btnEstudiantesMouseExited

    private void btnEducadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEducadorMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnEducador, "entrada");
    }//GEN-LAST:event_btnEducadorMouseEntered

    private void btnEducadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEducadorMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnEducador,"salida");
    }//GEN-LAST:event_btnEducadorMouseExited

    private void btnAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnAdmin, "entrada");
    }//GEN-LAST:event_btnAdminMouseEntered

    private void btnAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnAdmin, "salida");
    }//GEN-LAST:event_btnAdminMouseExited

    private void btnCursoCreadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursoCreadoMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnCursoCreado,"entrada");
    }//GEN-LAST:event_btnCursoCreadoMouseEntered

    private void btnCursoCreadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursoCreadoMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnCursoCreado, "salida");
    }//GEN-LAST:event_btnCursoCreadoMouseExited

    private void btnCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnCursos,"entrada");
    }//GEN-LAST:event_btnCursosMouseEntered

    private void btnCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnCursos,"salida");
    }//GEN-LAST:event_btnCursosMouseExited

    private void btnChatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChatMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnChat, "entrada");
    }//GEN-LAST:event_btnChatMouseEntered

    private void btnChatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChatMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnChat, "salida");
    }//GEN-LAST:event_btnChatMouseExited

    private void btnConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnConfig,"entrada");
    }//GEN-LAST:event_btnConfigMouseEntered

    private void btnConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnConfig,"salida");
    }//GEN-LAST:event_btnConfigMouseExited

    private void btnInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnInfo,"entrada");
    }//GEN-LAST:event_btnInfoMouseEntered

    private void btnInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnInfo, "salida");
    }//GEN-LAST:event_btnInfoMouseExited

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        crearUsuario editar;
        try {
            editar = new crearUsuario("actualizacion", correo,"login",controlador);
            editar.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
                    new Administrador().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnCursoCreado;
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnEducador;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel laboNombre;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbNomApellidos;
    private javax.swing.JLabel lbNomEmail;
    private javax.swing.JLabel lbNomHora;
    private javax.swing.JLabel lbNomNombres;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNomfecha;
    private javax.swing.JLabel lbPerfilUsuario;
    private javax.swing.JLabel lbTiposCursos;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel pEstudiante;
    private javax.swing.JPanel panelPerfilDos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel umss;
    // End of variables declaration//GEN-END:variables
}
