/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Controlador.Controlador;
import Paneles.examenes;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Jazz
 */
public class CrearPreguntas extends javax.swing.JFrame {

    private Controlador controlador;
    
    private int idExamen;
    private int idPregunta;
    private examenes examenes;

    /**
     * Creates new form CrearPreguntas
     */
    public CrearPreguntas() {
        initComponents();
    }
    //metodo que permite cambiar el icono de la plataformaen la barar de tareas de windows
     public Image getIconImage(){       
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/info_sistemas.png"));       
        return retvalue;  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        txtNombre = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRespuesta1 = new javax.swing.JLabel();
        txtRespuesta2 = new javax.swing.JLabel();
        txtRespuesta3 = new javax.swing.JLabel();
        txtRespuesta4 = new javax.swing.JLabel();
        tfRes1 = new javax.swing.JTextField();
        tfRes2 = new javax.swing.JTextField();
        tfRes3 = new javax.swing.JTextField();
        tfRes4 = new javax.swing.JTextField();
        tfPre = new javax.swing.JTextField();
        cbRes = new javax.swing.JComboBox<>();
        cbRes1 = new javax.swing.JComboBox<>();
        cbRes2 = new javax.swing.JComboBox<>();
        cbRes3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPreguntas = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRespuestas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar Preguntas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESAR PREGUNTAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 40, -1, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 11, 90, 30));

        txtNombre.setText("nombre");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 84, -1, -1));

        txtFecha.setText("Fecha");
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 84, -1, -1));

        jLabel2.setText("Pregunta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        txtRespuesta1.setText("Respuesta 1:");
        getContentPane().add(txtRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, -1, -1));

        txtRespuesta2.setText("Respuesta 2:");
        getContentPane().add(txtRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, -1, -1));

        txtRespuesta3.setText("Respuesta 3:");
        getContentPane().add(txtRespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txtRespuesta4.setText("Respuesta 4:");
        getContentPane().add(txtRespuesta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, -1, -1));
        getContentPane().add(tfRes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 140, 500, 30));
        getContentPane().add(tfRes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 176, 500, 30));
        getContentPane().add(tfRes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 212, 500, 30));
        getContentPane().add(tfRes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 248, 500, 30));
        getContentPane().add(tfPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 104, 500, 30));

        cbRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Falsa", "Verdadera" }));
        getContentPane().add(cbRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 100, 30));

        cbRes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Falsa", "Verdadera" }));
        getContentPane().add(cbRes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 176, 100, 30));

        cbRes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Falsa", "Verdadera" }));
        getContentPane().add(cbRes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 212, 100, 30));

        cbRes3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Falsa", "Verdadera" }));
        getContentPane().add(cbRes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 248, 100, 30));

        tbPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPreguntasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPreguntas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 350, 177));

        btnInsertar.setText("Insertar Pregunta");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 308, 180, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 300, 100, -1));

        btnEliminar.setText("Eliminar Pregunta");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 100, -1));

        tbRespuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbRespuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRespuestasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbRespuestas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 350, 177));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarPreguntas(){
        tbPreguntas.setModel(controlador.getPreguntas(idExamen));
    }
    private void limpiar(){
        tfPre.setText("");
        tfRes1.setText("");
        tfRes2.setText("");
        tfRes3.setText("");
        tfRes4.setText("");
        cbRes.setSelectedIndex(0);
        cbRes1.setSelectedIndex(0);
        cbRes2.setSelectedIndex(0);
        cbRes3.setSelectedIndex(0);
    }
    public void llenarTablaPreguntas(){
    int fila = tbPreguntas.getSelectedRow();
        if(fila >= 0){
            String idPregunta = tbPreguntas.getValueAt(fila, 0).toString();
            this.idPregunta = Integer.parseInt(idPregunta);
            try{
            tbRespuestas.setModel(controlador.getRespuestas(idPregunta));
            
            
            tfPre.setText(tbPreguntas.getValueAt(fila, 1).toString());
            tfRes1.setText(tbRespuestas.getValueAt(0, 1).toString());
            if(tbRespuestas.getValueAt(0, 2).toString().equalsIgnoreCase("F"))
                cbRes.setSelectedIndex(0);
            else
                cbRes.setSelectedIndex(1);
            tfRes2.setText(tbRespuestas.getValueAt(1, 1).toString());
            if(tbRespuestas.getValueAt(1, 2).toString().equalsIgnoreCase("F"))
                cbRes1.setSelectedIndex(0);
            else
                cbRes1.setSelectedIndex(1);
            tfRes3.setText(tbRespuestas.getValueAt(2, 1).toString());
            if(tbRespuestas.getValueAt(2, 2).toString().equalsIgnoreCase("F"))
                cbRes2.setSelectedItem("Falsa");
            else
                cbRes2.setSelectedIndex(1);
            tfRes4.setText(tbRespuestas.getValueAt(3, 1).toString());
            if(tbRespuestas.getValueAt(3, 2).toString().equalsIgnoreCase("F"))
                cbRes3.setSelectedIndex(0);
            else
                cbRes3.setSelectedIndex(1);
            }
            catch(Exception e){JOptionPane.showMessageDialog(null, "no esta completa la pregunta");}
        }
    }
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        examenes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        boolean res = controlador.setPreguntas(idExamen, tfPre.getText(), tfRes1.getText(), tfRes2.getText(), tfRes3.getText(), tfRes4.getText(),
                cbRes.getSelectedIndex(), cbRes1.getSelectedIndex(), cbRes2.getSelectedIndex(), cbRes3.getSelectedIndex());
        if(res)
            JOptionPane.showMessageDialog(null, "Se Actualizo con exito");
        else
            JOptionPane.showMessageDialog(null, "error");
        mostrarPreguntas();
        llenarTablaPreguntas();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tbPreguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPreguntasMouseClicked
        llenarTablaPreguntas();
    }//GEN-LAST:event_tbPreguntasMouseClicked

    private void tbRespuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRespuestasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRespuestasMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        boolean res = controlador.updatePreguntaRespuesta(idExamen, idPregunta, tfPre.getText(), tfRes1.getText(), tfRes2.getText(), tfRes3.getText(), tfRes4.getText(),
                cbRes.getSelectedIndex(), cbRes1.getSelectedIndex(), cbRes2.getSelectedIndex(), cbRes3.getSelectedIndex());
        if(res)
            JOptionPane.showMessageDialog(null, "se guardo con exito");
        else
            JOptionPane.showMessageDialog(null, "error");
        mostrarPreguntas();
        llenarTablaPreguntas();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tbPreguntas.getSelectedRow();
        if(fila >= 0){
            int idPregunta = Integer.parseInt(tbPreguntas.getValueAt(fila, 0).toString());
            boolean eliminar = controlador.eliminarPregunta(idPregunta);
            if(eliminar)
                JOptionPane.showMessageDialog(null, "Se elimino con exito");
            else
                JOptionPane.showMessageDialog(null, "Error al eliminar");
        }else
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        mostrarPreguntas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPreguntas().setVisible(true);
            }
        });
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JComboBox<String> cbRes;
    private javax.swing.JComboBox<String> cbRes1;
    private javax.swing.JComboBox<String> cbRes2;
    private javax.swing.JComboBox<String> cbRes3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbPreguntas;
    private javax.swing.JTable tbRespuestas;
    private javax.swing.JTextField tfPre;
    private javax.swing.JTextField tfRes1;
    private javax.swing.JTextField tfRes2;
    private javax.swing.JTextField tfRes3;
    private javax.swing.JTextField tfRes4;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtRespuesta1;
    private javax.swing.JLabel txtRespuesta2;
    private javax.swing.JLabel txtRespuesta3;
    private javax.swing.JLabel txtRespuesta4;
    // End of variables declaration//GEN-END:variables

    public void setDatos(int idExamen, String nombre, String fecha) {
        txtNombre.setText(nombre);
        txtFecha.setText(fecha);
        this.idExamen = idExamen;
    }

    public void setCrearExamenes(examenes examenes) {
        this.examenes = examenes;
    }
}
