/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Controlador.Controlador;
import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import methods.*;
import hilos.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import Paneles.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author JORGE DELGADILLO
 */

public class Educador extends javax.swing.JFrame {

    /**
     * Creates new form Educador
     */
      //instanciamo la clase para el cambio de tamaño 
    cambioTamaño cambio = new cambioTamaño();
    //instanciomos la clase para hacer el cambio de los paneles para navegar
    cambioPaneles cambioPanel = new cambioPaneles();
    //instanciamos la clase para el reloj y la fecha
    reloj_fecha reloj = new reloj_fecha();
    
    private String correo;
    
     private String tipo;
    
    int x,y;
    
    botones boton = new botones();

     private Controlador controlador;
    private login login;
    
    public Educador() {
        
        this.correo = "";
        
         this.tipo = "educador";
         
        this.controlador = null;
        initComponents();
        //ubicamos al centro de la pantalla
         setLocationRelativeTo(null);
        //ponemos un icono en el label para el fondo de pantalla
        lbFondo.setIcon(cambio.cambio(1240,720,"/img/fondo.png"));
         //hacemos el borde redondo
        Shape form = new RoundRectangle2D.Double(0,0,this.getBounds().width,this.getBounds().height,27,27);
        
        AWTUtilities.setWindowShape(this,form);
        //colocamos la hora 
        reloj.iniciar(lbHora, lbFecha);
        //metodo para hacer qeu el fondo se vea 
        //panelPerfil.setOpaque(true);
        lbPerfilUsuario.setIcon(cambio.cambio(150, 150, "/img/person.png"));
        //para el paneln d3l perfil 
        panelPerfil.setBackground(Color.red);
         
    }
    //metodo que permite cambiar el icono de la plataformaen la barar de tareas de windows
     public Image getIconImage(){       
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/info_sistemas.png"));       
        return retvalue;  
    }
    void setInicio() throws SQLException{
            cambioPanel.cambiar_panel("inicio",panelPrincipal,799,449,correo,tipo,controlador);
    }
    void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    void setLogin(login login) {
        this.login = login;
    }

    void setDatos(String[] datos,ImageIcon imagen) {
        
        lbUsuario.setText(datos[0]);
        lbNombre.setText(datos[1]);
        lbApellidos.setText(datos[2]);
        
        lbPerfilUsuario.setIcon(imagen);
        
    }
    void setCorreo(String correo){
        this.correo = correo;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPerfil = new javax.swing.JPanel();
        lbPerfilUsuario = new javax.swing.JLabel();
        lbNomEmail = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbNomNombres = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbNomApellidos = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        btnInformacionEdit = new javax.swing.JButton();
        lbNomHora = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        lbNomfecha = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        umss = new javax.swing.JLabel();
        laboNombre = new javax.swing.JLabel();
        pEstudiante = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnMisCursos = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        btnChat = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        btnCreados = new javax.swing.JButton();
        lbTiposCursos = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPerfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil del Usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lbNomEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNomEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbNomEmail.setText("Usuario :");

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbNomNombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNomNombres.setForeground(new java.awt.Color(255, 255, 255));
        lbNomNombres.setText("Nombres :");

        lbNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbNomApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNomApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lbNomApellidos.setText("Apellidos :");

        lbApellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lbApellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnInformacionEdit.setBackground(new java.awt.Color(204, 204, 255));
        btnInformacionEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInformacionEdit.setText("Editar Informacion");
        btnInformacionEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInformacionEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInformacionEditMouseExited(evt);
            }
        });
        btnInformacionEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPerfilLayout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(panelPerfilLayout);
        panelPerfilLayout.setHorizontalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInformacionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNomEmail))
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNomApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPerfilLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbNomNombres)))
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelPerfilLayout.setVerticalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lbPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(lbNomEmail)
                .addGap(18, 18, 18)
                .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNomNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNomApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnInformacionEdit)
                .addContainerGap())
        );

        getContentPane().add(panelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, 540));

        lbNomHora.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbNomHora.setForeground(new java.awt.Color(255, 255, 255));
        lbNomHora.setText("Hora:");
        getContentPane().add(lbNomHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lbHora.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 56, 130, 20));

        lbNomfecha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbNomfecha.setForeground(new java.awt.Color(255, 255, 255));
        lbNomfecha.setText("Fecha :");
        getContentPane().add(lbNomfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lbFecha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 96, 110, 20));

        umss.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        umss.setText("\" Universidad Mayor de San Simón \"");
        getContentPane().add(umss, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        laboNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laboNombre.setText("Laboratorios de Informática Sistemas");
        getContentPane().add(laboNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        pEstudiante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pEstudiante.setText("PLATAFORMA DEL ENCARGADO DEL CURSO");
        getContentPane().add(pEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, 80, 50));

        btnInicio.setBackground(new java.awt.Color(204, 204, 255));
        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 120, 80));

        btnMisCursos.setBackground(new java.awt.Color(204, 204, 255));
        btnMisCursos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMisCursos.setText("Inscritos");
        btnMisCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMisCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMisCursosMouseExited(evt);
            }
        });
        btnMisCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMisCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 120, 80));

        btnCursos.setBackground(new java.awt.Color(204, 204, 255));
        btnCursos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCursos.setText("Todos");
        btnCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCursosMouseExited(evt);
            }
        });
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 120, 80));

        btnChat.setBackground(new java.awt.Color(204, 204, 255));
        btnChat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnChat.setText("Mensajes");
        btnChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChatMouseExited(evt);
            }
        });
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });
        getContentPane().add(btnChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 120, 80));

        panelPrincipal.setOpaque(false);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 780, 520));

        btnCreados.setBackground(new java.awt.Color(204, 204, 255));
        btnCreados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreados.setText("Creados");
        btnCreados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreadosMouseExited(evt);
            }
        });
        btnCreados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreados, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 120, 80));

        lbTiposCursos.setText("Cursos:");
        getContentPane().add(lbTiposCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        lbFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbFondoMouseDragged(evt);
            }
        });
        lbFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbFondoMousePressed(evt);
            }
        });
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 1230, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        login.eliminarContraseña();
         login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        try {
            // cambiamos al panel inicio
            cambioPanel.cambiar_panel("inicio",panelPrincipal,799,449,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Educador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnMisCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisCursosActionPerformed

        try {
            // Cambiamos al panel mis cursos
            cambioPanel.cambiar_panel("misCursos",panelPrincipal,799,449,correo,"inscritos",controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Educador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMisCursosActionPerformed

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed

        try {
            // cambiamos al panel de todos los cursos
            cambioPanel.cambiar_panel("cursos",panelPrincipal,799,499,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Educador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        try {
            // cambiamos al panel mensajes
            cambioPanel.cambiar_panel("mensajes",panelPrincipal,799,449,correo,tipo,controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Educador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChatActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         setDatos(controlador.getDatosUsuario(correo),controlador.getImagenPerfil(correo));
    }//GEN-LAST:event_formWindowActivated

    private void lbFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFondoMouseDragged
        // movimiento de la ventana en la pantalla
        //capturamos la posicion del mause al moverlo 
        Point p = MouseInfo.getPointerInfo().getLocation();
        //movemos el frame en la direccion en la que arrastremos el mouse
        setLocation(p.x-x,p.y-y);
    }//GEN-LAST:event_lbFondoMouseDragged

    private void lbFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFondoMousePressed
        // mivimiento de la pantalla en la panatalla
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lbFondoMousePressed

    private void btnCreadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreadosActionPerformed
        try {
            // TODO add your handling code here:
            cambioPanel.cambiar_panel("misCursos",panelPrincipal,799,449,correo,"creados",controlador);
        } catch (SQLException ex) {
            Logger.getLogger(Educador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreadosActionPerformed

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        boton.cambioColorSalir(btnSalir, "entrada");
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        boton.cambioColorSalir(btnSalir,"salida");
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnInicio,"entrada");
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnInicio,"salida");
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnMisCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMisCursosMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnMisCursos,"entrada");
    }//GEN-LAST:event_btnMisCursosMouseEntered

    private void btnMisCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMisCursosMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnMisCursos, "salida");
    }//GEN-LAST:event_btnMisCursosMouseExited

    private void btnCreadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreadosMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnCreados,"entrada");
    }//GEN-LAST:event_btnCreadosMouseEntered

    private void btnCreadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreadosMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnCreados,"salida");
    }//GEN-LAST:event_btnCreadosMouseExited

    private void btnCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnCursos,"entrada");
    }//GEN-LAST:event_btnCursosMouseEntered

    private void btnCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnCursos,"salida");
    }//GEN-LAST:event_btnCursosMouseExited

    private void btnChatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChatMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnChat,"entrada");
    }//GEN-LAST:event_btnChatMouseEntered

    private void btnChatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChatMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnChat,"salida");
    }//GEN-LAST:event_btnChatMouseExited

    private void btnInformacionEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacionEditMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnInformacionEdit,"entrada");
    }//GEN-LAST:event_btnInformacionEditMouseEntered

    private void btnInformacionEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacionEditMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnInformacionEdit,"salida");
    }//GEN-LAST:event_btnInformacionEditMouseExited

    private void btnInformacionEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionEditActionPerformed
        try {
            // TODO add your handling code here
            crearUsuario editar = new crearUsuario("actualizacion", correo,"login",controlador);
            editar.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Educador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInformacionEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Educador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Educador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Educador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Educador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Educador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnCreados;
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnInformacionEdit;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMisCursos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel laboNombre;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbNomApellidos;
    private javax.swing.JLabel lbNomEmail;
    private javax.swing.JLabel lbNomHora;
    private javax.swing.JLabel lbNomNombres;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNomfecha;
    private javax.swing.JLabel lbPerfilUsuario;
    private javax.swing.JLabel lbTiposCursos;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel pEstudiante;
    private javax.swing.JPanel panelPerfil;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel umss;
    // End of variables declaration//GEN-END:variables
}
