/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Controlador.Controlador;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jazz
 */
public class ExamenEstudiante extends javax.swing.JFrame {

    private Controlador controlador;
    private String idUsuario;
    private int idCurso;
    private int idExamen;
    private ArrayList<String> listaPreguntas;
    private ArrayList<String> listaRespuestas;
    private ArrayList<Integer> listaVF;
    private ArrayList<Integer> listaLlenado;
    private int cont;
    int q,w;

    /**
     * Creates new form ExamenEstudiante
     */
    public ExamenEstudiante(){
        initComponents();
    }
    public ExamenEstudiante(String usuario,int idExamen, Controlador controlador, int idCurso) {
        this.idUsuario = usuario;
        this.idCurso = idCurso;
        this.idExamen = idExamen;
        this.controlador = controlador;
        initComponents();
        cont = 0;
        listaPreguntas = new ArrayList();
        listaRespuestas = new ArrayList();
        listaVF = new ArrayList();
        listaLlenado = new ArrayList();
        bg1.add(rb1V1);
        bg1.add(rb1F1);
        bg2.add(rb1V2);
        bg2.add(rb1F2);
        bg3.add(rb1V3);
        bg3.add(rb1F3);
        bg4.add(rb1V4);
        bg4.add(rb1F4);
        btnAnterior.setEnabled(false);
        
    }
    //metodo que permite cambiar el icono de la plataformaen la barar de tareas de windows
     public Image getIconImage(){       
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/info_sistemas.png"));       
        return retvalue;  
    }
    
    public void cargarDatos(){
        try{
        lblExamen.setText(controlador.getNombreExamen(idExamen));
        lblMateria.setText(controlador.getNombreCurso(idCurso));
        lblCantidad.setText(controlador.getCantidadExamen(idExamen));
        listaPreguntas = controlador.getListaPreguntas(idExamen);
        listaRespuestas = controlador.getListaRespuestas(idExamen);
        listaVF = controlador.getListaVF(idExamen);
            for (int i = 0; i < listaVF.size(); i++) {
                listaLlenado.add(0);
            }
        lblPregunta.setText(listaPreguntas.get(0));
        lblRes1.setText(listaRespuestas.get(0));
        lblRes2.setText(listaRespuestas.get(1));
        lblRes3.setText(listaRespuestas.get(2));
        lblRes4.setText(listaRespuestas.get(3));
        rb1F1.setSelected(true);
        rb1F2.setSelected(true);
        rb1F3.setSelected(true);
        rb1F4.setSelected(true);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, "El Examen aun no esta completo!");}
    }
    public void recogerRespuestas(){
        ArrayList<Integer> res = new ArrayList();    
        if(rb1V1.isSelected())
            res.add(1);
        else
            res.add(0);
        if(rb1V2.isSelected())
            res.add(1);
        else
            res.add(0);
        if(rb1V3.isSelected())
            res.add(1);
        else
            res.add(0);
        if(rb1V4.isSelected())
            res.add(1);
        else
            res.add(0);
        listaLlenado.set(cont*4 + 0, res.get(0));
        listaLlenado.set(cont*4 + 1, res.get(1));
        listaLlenado.set(cont*4 + 2, res.get(2));
        listaLlenado.set(cont*4 + 3, res.get(3));
    }
    public void llenarRespuestas(){
        if(listaLlenado.get(cont*4 + 0) == 1)
            rb1V1.setSelected(true);
        else
            rb1F1.setSelected(true);
        if(listaLlenado.get(cont*4 + 1) == 1)
            rb1V2.setSelected(true);
        else
            rb1F2.setSelected(true);
        if(listaLlenado.get(cont*4 + 2) == 1)
            rb1V3.setSelected(true);
        else
            rb1F3.setSelected(true);
        if(listaLlenado.get(cont*4 + 3) == 1)
            rb1V4.setSelected(true);
        else
            rb1F4.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        bg3 = new javax.swing.ButtonGroup();
        bg4 = new javax.swing.ButtonGroup();
        lblRes1 = new javax.swing.JLabel();
        rb1F1 = new javax.swing.JRadioButton();
        txtMateria = new javax.swing.JLabel();
        rb1F3 = new javax.swing.JRadioButton();
        lblRes4 = new javax.swing.JLabel();
        lblRes2 = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblRes3 = new javax.swing.JLabel();
        rb1V4 = new javax.swing.JRadioButton();
        txtExamen = new javax.swing.JLabel();
        rb1V3 = new javax.swing.JRadioButton();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        rb1F2 = new javax.swing.JRadioButton();
        lblCantidad = new javax.swing.JLabel();
        txtRes1 = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        txtRes2 = new javax.swing.JLabel();
        lblExamen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rb1V2 = new javax.swing.JRadioButton();
        txtCantidadPreguntas = new javax.swing.JLabel();
        rb1F4 = new javax.swing.JRadioButton();
        txtPregunta = new javax.swing.JLabel();
        rb1V1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtRes3 = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        txtRes4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRes1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        getContentPane().add(lblRes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 185, 600, 30));
        getContentPane().add(rb1F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 185, -1, -1));

        txtMateria.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtMateria.setText("Curso:");
        getContentPane().add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 77, -1, 30));
        getContentPane().add(rb1F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 247, -1, -1));

        lblRes4.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        getContentPane().add(lblRes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 293, 600, 30));

        lblRes2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        getContentPane().add(lblRes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 221, 600, 30));

        btnFinalizar.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 341, 150, 30));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setText("V");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 149, 20, 30));

        lblRes3.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        getContentPane().add(lblRes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 257, 600, 30));
        getContentPane().add(rb1V4, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 271, -1, -1));

        txtExamen.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtExamen.setText("Examen:");
        getContentPane().add(txtExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 77, -1, 30));
        getContentPane().add(rb1V3, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 247, -1, -1));

        btnSiguiente.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 341, 150, 30));

        btnAnterior.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 341, 150, 30));
        getContentPane().add(rb1F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 216, -1, -1));

        lblCantidad.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        getContentPane().add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 113, 616, 30));

        txtRes1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtRes1.setText("R1:");
        getContentPane().add(txtRes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 185, -1, 30));

        lblMateria.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        getContentPane().add(lblMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 77, 272, 30));

        txtRes2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtRes2.setText("R2:");
        getContentPane().add(txtRes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 221, -1, 30));

        lblExamen.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        getContentPane().add(lblExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 77, 452, 30));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel3.setText("Lea bien las preguntas antes de responder!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 434, -1, -1));
        getContentPane().add(rb1V2, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 216, -1, -1));

        txtCantidadPreguntas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtCantidadPreguntas.setText("Cantidad Preguntas:");
        getContentPane().add(txtCantidadPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 113, -1, 30));
        getContentPane().add(rb1F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 271, -1, -1));

        txtPregunta.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtPregunta.setText("Pregunta:");
        getContentPane().add(txtPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 149, -1, 30));
        getContentPane().add(rb1V1, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 185, -1, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel2.setText("F");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 149, 20, 30));

        jButton1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 18, 150, 30));

        txtRes3.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtRes3.setText("R3:");
        getContentPane().add(txtRes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 257, -1, 30));

        lblPregunta.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        getContentPane().add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 149, 600, 30));

        txtRes4.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtRes4.setText("R4:");
        getContentPane().add(txtRes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 293, -1, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
         q = evt.getX();
        w = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //capturamos la posicion del mause al moverlo 
        Point p = MouseInfo.getPointerInfo().getLocation();
        //movemos el frame en la direccion en la que arrastremos el mouse
        setLocation(p.x-q,p.y-w);
    }//GEN-LAST:event_formMouseDragged

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        recogerRespuestas();
        boolean exito = controlador.guardarCalificacion(idUsuario, idCurso, idExamen, listaVF, listaLlenado);
        int intento = controlador.getIntentosRea(idExamen);
        if(exito){
            intento++;
            boolean res = controlador.actualizarIntentosRea(idExamen, intento);
            if(res)
                JOptionPane.showMessageDialog(null, "Realizanste: " + intento + " intento.");
            else
                JOptionPane.showMessageDialog(null, "Sin Conexion a la Base de datos");
        }
        else
            JOptionPane.showMessageDialog(null, "Sin Conexion a la Base de datos");
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
         int max = listaPreguntas.size();

        if( this.cont +1 < max){
            recogerRespuestas();

            this.cont++;
            System.out.println(cont);
            llenarRespuestas();
            lblPregunta.setText(listaPreguntas.get(cont));
            lblRes1.setText(listaRespuestas.get(cont*4 + 0));
            lblRes2.setText(listaRespuestas.get(cont*4 + 1));
            lblRes3.setText(listaRespuestas.get(cont*4 + 2));
            lblRes4.setText(listaRespuestas.get(cont*4 + 3));
            btnAnterior.setEnabled(true);
        }
        else{
            recogerRespuestas();
            btnSiguiente.setEnabled(false);
            System.out.println(cont + " else");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (cont - 1>= 0) {
            recogerRespuestas();
            

            cont--;
            System.out.println(cont);
            llenarRespuestas();
            lblPregunta.setText(listaPreguntas.get(cont));
            lblRes1.setText(listaRespuestas.get(cont*4 + 0));
            lblRes2.setText(listaRespuestas.get(cont*4 + 1));
            lblRes3.setText(listaRespuestas.get(cont*4 + 2));
            lblRes4.setText(listaRespuestas.get(cont*4 + 3)); 
            btnSiguiente.setEnabled(true);
        }else{
            recogerRespuestas();
            btnAnterior.setEnabled(false);
            System.out.println(cont + " else");            
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamenEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamenEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamenEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamenEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamenEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.ButtonGroup bg3;
    private javax.swing.ButtonGroup bg4;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblExamen;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblRes1;
    private javax.swing.JLabel lblRes2;
    private javax.swing.JLabel lblRes3;
    private javax.swing.JLabel lblRes4;
    private javax.swing.JRadioButton rb1F1;
    private javax.swing.JRadioButton rb1F2;
    private javax.swing.JRadioButton rb1F3;
    private javax.swing.JRadioButton rb1F4;
    private javax.swing.JRadioButton rb1V1;
    private javax.swing.JRadioButton rb1V2;
    private javax.swing.JRadioButton rb1V3;
    private javax.swing.JRadioButton rb1V4;
    private javax.swing.JLabel txtCantidadPreguntas;
    private javax.swing.JLabel txtExamen;
    private javax.swing.JLabel txtMateria;
    private javax.swing.JLabel txtPregunta;
    private javax.swing.JLabel txtRes1;
    private javax.swing.JLabel txtRes2;
    private javax.swing.JLabel txtRes3;
    private javax.swing.JLabel txtRes4;
    // End of variables declaration//GEN-END:variables

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }

    public void setIdExamen(int idExamen) {
        this.idExamen = idExamen;
    }
}
