/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Controlador.Controlador;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JORGE DELGADILLO
 */
public class anunciosCursos extends javax.swing.JPanel {

    /**
     * Creates new form anunciosCursos
     */
    private Controlador controlador;
    private String idCurso;
    private String tipo;
    public anunciosCursos(String idCurso,Controlador controlador,String tipo){
        
        this.controlador = controlador;
        
        this.tipo = tipo;
        
        this.idCurso = idCurso;
        
        initComponents();
        setOpaque(false);
        
        txtAnuncios.setEditable(false);
        
        txtAnuncios.setLineWrap(true);
        
        colocarMensajes();
        
    }
    private void colocarMensajes(){
        ArrayList<String> mensajes = controlador.dameAnuncios(Integer.parseInt(idCurso));
            for(int i = 0 ;i<mensajes.size();i++){
                
                if (i == 0){
                    txtAnuncios.append("________________________________________________________________________________________________________\n");
                    txtAnuncios.append("\n");
                    txtAnuncios.append("---->  "+mensajes.get(i)+"\n");
                    txtAnuncios.append("\n");
                    txtAnuncios.append("________________________________________________________________________________________________________\n");
               }else{
                    txtAnuncios.append("\n");
                    txtAnuncios.append("---->  "+mensajes.get(i)+"\n");  
                    txtAnuncios.append("\n");
                    txtAnuncios.append("________________________________________________________________________________________________________\n");
               }
                
            }
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAnuncios = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANUNCIOS DEL CURSO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        txtAnuncios.setColumns(20);
        txtAnuncios.setRows(5);
        jScrollPane1.setViewportView(txtAnuncios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAnuncios;
    // End of variables declaration//GEN-END:variables
}
