/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Controlador.Controlador;
import forms.CrearPreguntas;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class examenes extends javax.swing.JPanel {

    /**
     * Creates new form examenes
     */
    String nombre;
    String tipo;
    private Controlador controlador;
    CrearPreguntas crearPreguntas;
   
    private int idCurso;
    private int idExamen;
    
    
    public examenes(String nombre ,String tipo, Controlador controlador, int idUsuario) {
        
        initComponents();
        this.nombre = nombre;
        this.tipo = tipo;
        this.controlador = controlador;
        
        this.idCurso = idUsuario;
        crearPreguntas = new CrearPreguntas();
        mostrarExamenes();
        setOpaque(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spHI = new javax.swing.JSpinner();
        spMI = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        spHF = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spMF = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spTiempo = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPreguntas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbExamen = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        tfNombreExamen = new javax.swing.JTextField();
        btnHabilitar = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();
        txtIntentos = new javax.swing.JLabel();
        cbIntentos = new javax.swing.JComboBox<>();
        fechaExamen = new com.toedter.calendar.JDateChooser();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Examenes"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spHI.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        add(spHI, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 104, 40, 30));

        spMI.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        add(spMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 104, 65, 30));

        jLabel1.setText("Nombre examen:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, -1));

        spHF.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        add(spHF, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 144, 40, 30));

        jLabel2.setText("Fecha examen:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        spMF.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        add(spMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 144, 65, 30));

        jLabel3.setText("Hora Inicio:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, 30));

        spTiempo.setModel(new javax.swing.SpinnerNumberModel(30, 0, 480, 5));
        add(spTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 185, 42, 30));

        jLabel4.setText("Hora Fin:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, -1, 30));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 234, 135, 30));

        jLabel5.setText("Tiempo minutos:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        btnPreguntas.setText("++ Preguntas");
        btnPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntasActionPerformed(evt);
            }
        });
        add(btnPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 234, 135, 30));

        tbExamen.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Preguntas"));
        tbExamen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbExamen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbExamenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbExamen);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 760, 153));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 234, 135, 30));
        add(tfNombreExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 34, 170, 30));

        btnHabilitar.setText("Habilitar");
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });
        add(btnHabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 234, 135, 30));

        btnDeshabilitar.setText("Deshabilitar");
        btnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarActionPerformed(evt);
            }
        });
        add(btnDeshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 234, 135, 30));

        txtIntentos.setText("Numero de Intentos:");
        add(txtIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 30));

        cbIntentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        add(cbIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 60, 30));
        add(fechaExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 74, 167, 24));
    }// </editor-fold>//GEN-END:initComponents
    
    public void mostrarExamenes(){
        try{
            tbExamen.setModel(controlador.llenarTablaExamenesCurso(idCurso));
        }catch(Exception e){JOptionPane.showMessageDialog(null, e.toString());}
        
    }
    
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombreExamen = tfNombreExamen.getText();
        String fechaEx = fechaExamen.getDate().toString();
        String horaInicio = spHI.getValue().toString();
        String minutoInicio = spMI.getValue().toString();
        String horaFin = spHF.getValue().toString();
        String minutoFin = spMF.getValue().toString();
        String tiempo = spTiempo.getValue().toString();
        int intentos = Integer.parseInt(cbIntentos.getSelectedItem().toString());
        boolean res = controlador.insertarExamen(idCurso, nombreExamen, fechaEx, horaInicio, minutoInicio,
            horaFin, minutoFin, tiempo, intentos);
        if(res)
        JOptionPane.showMessageDialog(null, "se creo con exito");
        else
        JOptionPane.showMessageDialog(null, "en implementacion!");
        mostrarExamenes();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntasActionPerformed
        int fila = tbExamen.getSelectedRow();
        if(fila >= 0){
            crearPreguntas.setControlador(controlador);
            crearPreguntas.setCrearExamenes(this);
            int examenID = Integer.parseInt(tbExamen.getValueAt(fila, 0).toString());
            System.out.println(examenID);
            crearPreguntas.setDatos(examenID, tbExamen.getValueAt(fila, 1).toString(), tbExamen.getValueAt(fila, 2).toString());
            crearPreguntas.mostrarPreguntas();
            crearPreguntas.setVisible(true);
            this.setVisible(false);
        }else JOptionPane.showMessageDialog(null, "seleccione un examen");

    }//GEN-LAST:event_btnPreguntasActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tbExamen.getSelectedRow();
        if(fila >= 0){
            int examenID = Integer.parseInt(tbExamen.getValueAt(fila, 0).toString());
            boolean eliminado = controlador.eliminarExamen(examenID);
            String examen = tbExamen.getValueAt(fila, 1).toString();
            if(eliminado){
                JOptionPane.showMessageDialog(null, "se elimino con exito el examen: " + examen);
                mostrarExamenes();      
            }
            else
                JOptionPane.showMessageDialog(null, "Error al conectar a la base de datos");
        }else JOptionPane.showMessageDialog(null, "seleccione un examen");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
        if(idExamen > 0){
            boolean exito = controlador.habilitarExamen(idExamen);
            if(exito){
                this.mostrarExamenes();
                JOptionPane.showMessageDialog(null, "Se habilito el examen: " + controlador.getNombreExamen(idExamen));
            }
            else
                JOptionPane.showMessageDialog(null, "Error en la conexion a la base de datos!");
        }else
            JOptionPane.showMessageDialog(null, "seleccione un examen!");
    }//GEN-LAST:event_btnHabilitarActionPerformed

    private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarActionPerformed
        if(idExamen > 0){
            boolean exito = controlador.deshabilitarExamen(idExamen);
            if(exito){
                this.mostrarExamenes();
                JOptionPane.showMessageDialog(null, "Se deshabilito el examen: " + controlador.getNombreExamen(idExamen));
            }
            else
                JOptionPane.showMessageDialog(null, "Error en la conexion a la base de datos!");
        }else
            JOptionPane.showMessageDialog(null, "seleccione un examen!");
    }//GEN-LAST:event_btnDeshabilitarActionPerformed

    private void tbExamenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbExamenMouseClicked
        int fila = tbExamen.getSelectedRow();
        if(fila >= 0){
            this.idExamen = Integer.parseInt(tbExamen.getValueAt(fila, 0).toString());
        }
    }//GEN-LAST:event_tbExamenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JButton btnPreguntas;
    private javax.swing.JComboBox<String> cbIntentos;
    private com.toedter.calendar.JDateChooser fechaExamen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spHF;
    private javax.swing.JSpinner spHI;
    private javax.swing.JSpinner spMF;
    private javax.swing.JSpinner spMI;
    private javax.swing.JSpinner spTiempo;
    private javax.swing.JTable tbExamen;
    private javax.swing.JTextField tfNombreExamen;
    private javax.swing.JLabel txtIntentos;
    // End of variables declaration//GEN-END:variables
    public void setControlador(Controlador controlador){
        this.controlador = controlador;
    }
}
