/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Controlador.Controlador;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author JORGE DELGADILLO
 */
public class inicio extends javax.swing.JPanel {

    /**
     * Creates new form inicio
     */
    
    
    private Controlador controlador;
    //instanciamos las clases para hacer las consultas 
    
    
    public inicio(Controlador controlador) {
     
        
        this.controlador = controlador;
        
        initComponents();
       
        setOpaque(false);
        
        txtMensajesNuevos.setEditable(false);
        
        txtMensajesNuevos.setLineWrap(true);
        
   
        
        try {
            colocarMensajes();
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void colocarMensajes() throws SQLException{
            ArrayList<String> mensajes = controlador.mensajesInicio();
            for(int i = 0 ;i<mensajes.size();i++){
                
                if (i == 0){
                    txtMensajesNuevos.append("________________________________________________________________________________________________________\n");
                    txtMensajesNuevos.append("\n");
                    txtMensajesNuevos.append("---->  "+mensajes.get(i)+"\n");
                    txtMensajesNuevos.append("\n");
                    txtMensajesNuevos.append("________________________________________________________________________________________________________\n");
               }else{
                    txtMensajesNuevos.append("\n");
                    txtMensajesNuevos.append("---->  "+mensajes.get(i)+"\n");  
                    txtMensajesNuevos.append("\n");
                    txtMensajesNuevos.append("________________________________________________________________________________________________________\n");
               }
                
            }
            
                 
        }
        
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensajesNuevos = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NUEVOS MENSAJES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 450));

        txtMensajesNuevos.setColumns(20);
        txtMensajesNuevos.setRows(5);
        jScrollPane1.setViewportView(txtMensajesNuevos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMensajesNuevos;
    // End of variables declaration//GEN-END:variables
}
