/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Controlador.Controlador;
import forms.ExamenEstudiante;
import javax.swing.JOptionPane;
import methods.*;

/**
 *
 * @author Jazz
 */
public class ListaExamenesEstudiante extends javax.swing.JPanel {

    private int idCurso;
    private String tipo;
    private Controlador controlador;
    private String idUsuario;
    private int idExamen;
    private ExamenEstudiante examenEstudiante;

    /**
     * Creates new form ListaExamenesEstudiante
     */
    botones boton = new botones();
    public ListaExamenesEstudiante() {
        initComponents();
    }

    public ListaExamenesEstudiante(String usuario, String tipo, Controlador controlador, int idCurso) {
        initComponents();
        this.idCurso = idCurso;
        this.tipo = tipo;
        this.controlador = controlador;
        this.idUsuario = usuario;
        lblMateria.setText(controlador.getNombreCurso(idCurso));
        llenarTabla();
        btnIngresar.setEnabled(false);
        setOpaque(false);
    }
    public void llenarTabla(){
        tbListaExamenes.setModel(controlador.getExamenesCursoEstudiante(idCurso, idUsuario));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMateria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaExamenes = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        lblMateria = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Examenes"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMateria.setText("Materia:");
        add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, 30));

        tbListaExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbListaExamenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaExamenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListaExamenes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 620, 310));

        btnIngresar.setBackground(new java.awt.Color(204, 204, 255));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 140, 40));
        add(lblMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 27, 416, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        int intentosMax = controlador.getIntentosMax(idExamen);
        int intentosRea = controlador.getIntentosRea(idExamen);
        System.out.println(intentosMax + ",  " + intentosRea);
        if(intentosRea < intentosMax){
            examenEstudiante = new ExamenEstudiante(idUsuario,idExamen,controlador,idCurso);
            //examenEstudiante.setControlador(controlador);
            //examenEstudiante.setIdUsuario(idUsuario);
            //examenEstudiante.setIdCurso(idCurso);
            //examenEstudiante.setIdExamen(idExamen);
            examenEstudiante.cargarDatos();
            examenEstudiante.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Ya no tienes intentos para realizar este examen!");
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void tbListaExamenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaExamenesMouseClicked
        int fila = tbListaExamenes.getSelectedRow();
        if(fila >= 0){
            this.idExamen = Integer.parseInt(tbListaExamenes.getValueAt(fila, 0).toString());
            btnIngresar.setEnabled(true);
        }
    }//GEN-LAST:event_tbListaExamenesMouseClicked

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        // TODO add your handling code here:
       boton.cambioColor(btnIngresar, "entrada");
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnIngresar, "salida");
    }//GEN-LAST:event_btnIngresarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JTable tbListaExamenes;
    private javax.swing.JLabel txtMateria;
    // End of variables declaration//GEN-END:variables
}
