/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;
import Controlador.Controlador;
import conexionBD.conexion;
import forms.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import methods.*;
/**
 *
 * @author JORGE DELGADILLO
 */
public class recibidos extends javax.swing.JPanel {

    /**
     * Creates new form recibidos
     */
    private String usuario ;
    
    private String tipo;
    
    botones boton = new botones ();
    
    private Controlador controlador;
    
    public recibidos(String usuario,String tipo,Controlador controlador) throws SQLException {
        
        this.usuario = usuario ;
        
        this.tipo = tipo;
        
        this.controlador = controlador;
        
        initComponents();
 
        setOpaque(false);
        
        mostrarTabla();
        
        
    }
    public void mostrarTabla() throws SQLException{
    
        DefaultTableModel modelo = controlador.mensajes(usuario, "recibido");
        tableRecibidos.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableRecibidos = new javax.swing.JTable();
        btnVer = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mensajes Recibidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableRecibidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableRecibidos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 520, 280));

        btnVer.setBackground(new java.awt.Color(204, 204, 255));
        btnVer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVer.setText("Ver Mensaje");
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerMouseExited(evt);
            }
        });
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 180, 50));

        btnEliminar.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setText("Eliminar Mensaje");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 180, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        String de = "";
        String asunto = "";
        String Mensaje = "";
         int fila = tableRecibidos.getSelectedRow();
        if(fila >= 0){
           de = (String) tableRecibidos.getValueAt(fila,1);
            asunto= tableRecibidos.getValueAt(fila, 2).toString();
            Mensaje = tableRecibidos.getValueAt(fila,3).toString();

        }else{
        JOptionPane.showMessageDialog(null,"Fila no seleccionada");
        }
        MensajeVisual mensaje = new MensajeVisual(de,asunto,Mensaje);
        mensaje.setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnVerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnVer,"entrada");
    }//GEN-LAST:event_btnVerMouseEntered

    private void btnVerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnVer,"salida");
    }//GEN-LAST:event_btnVerMouseExited

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         String idMensaje = "";
         int fila = tableRecibidos.getSelectedRow();
        if(fila >= 0){
           idMensaje = (String) tableRecibidos.getValueAt(fila,0);
           if(controlador.eliminarMensaje(idMensaje)){
                JOptionPane.showMessageDialog(null, "Mensaje Eliminado");
               try {
                   mostrarTabla();
               } catch (SQLException ex) {
                   Logger.getLogger(Enviados.class.getName()).log(Level.SEVERE, null, ex);
               }
           }else{
               JOptionPane.showMessageDialog(null,"Nose pudo eliminar el mensaje seleccionado");
           }

        }else{
        JOptionPane.showMessageDialog(null,"Fila no seleccionada");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnEliminar,"entrada");
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnEliminar,"salida");
    }//GEN-LAST:event_btnEliminarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRecibidos;
    // End of variables declaration//GEN-END:variables
}
