/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;
import Controlador.Controlador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import methods.*;
/**
 *
 * @author JORGE DELGADILLO
 */
public class totalCursos extends javax.swing.JPanel {

    /**
     * Creates new form totalCursos
     */
    private String usuario ;
    
    private String tipo;
    
    botones boton = new botones();
    
    private Controlador controlador ;

    public totalCursos(String usuario,String tipo,Controlador controlador) {
        
        this.usuario = usuario ;
        
        this.tipo = tipo;
        
        this.controlador = controlador;
        
        initComponents();
        
         if(tipo.equals("administrador")){
             btnEliminar.setVisible(false);
        }
        
        setOpaque(false);
        
        ponerTabla();
        
        if(tipo.equals("educador") || tipo.equals("estudiantes")){
            btnEliminar.setVisible(false);
            btnEliminar.setEnabled(false);
        }else{
            btnEliminar.setVisible(true);
            btnEliminar.setEnabled(true);
            btnInscripcion.setVisible(false);
            btnInscripcion.setEnabled(false);
        }
    }
    
    void ponerTabla(){
        
        if(tipo.equals("administrador")){
            DefaultTableModel modelo = controlador.dameCursosGlobalesAdministracion(usuario);
            tableCursosTotales.setModel(modelo);
        }else{
            DefaultTableModel modelo = controlador.glabalCursos(usuario);
            tableCursosTotales.setModel(modelo);
        }
        
        
        
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCursosTotales = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnInscripcion = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Todos los Cursos en la plataforma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCursosTotales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableCursosTotales);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 550, 350));

        btnEliminar.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setText("Eliminar Curso");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 190, 60));

        btnInscripcion.setBackground(new java.awt.Color(204, 204, 255));
        btnInscripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInscripcion.setText("INSCRIBIRSE");
        btnInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInscripcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInscripcionMouseExited(evt);
            }
        });
        btnInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionActionPerformed(evt);
            }
        });
        add(btnInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 190, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnEliminar,"entrada");
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnEliminar,"salida");
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnInscripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInscripcionMouseEntered
        // TODO add your handling code here:
        boton.cambioColor(btnInscripcion,"entrada");
    }//GEN-LAST:event_btnInscripcionMouseEntered

    private void btnInscripcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInscripcionMouseExited
        // TODO add your handling code here:
        boton.cambioColor(btnInscripcion,"salida");
    }//GEN-LAST:event_btnInscripcionMouseExited

    private void btnInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionActionPerformed
        // TODO add your handling code here:
        
         int fila = tableCursosTotales.getSelectedRow();
        if(fila >= 0){
          
            int id  = Integer.parseInt(tableCursosTotales.getValueAt(fila,0).toString());
            if(!controlador.existeInscripcion(id, usuario)){
                if(controlador.inscribirse(id, usuario)){
                
                    JOptionPane.showMessageDialog(null,"Incripcion realizada vaya a mis cursos para poder ingresar");
                
                }else{
                    JOptionPane.showMessageDialog(null,"No se pudo realizar la inscripcion");
                }

            }else{
                JOptionPane.showMessageDialog(null,"Usted ya esta inscrito en este curso ");
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Fila no seleccionada");
        }
        
    }//GEN-LAST:event_btnInscripcionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tableCursosTotales.getSelectedRow();
        if(fila >= 0){
          
            int id  = Integer.parseInt(tableCursosTotales.getValueAt(fila,0).toString());
            if(controlador.eliminarCurso(id)){
                JOptionPane.showMessageDialog(null,"Curso eliminado exitosamente");
            }else{
                JOptionPane.showMessageDialog(null,"Hubo un error al eliminar el curso");
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Fila no seleccionada");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInscripcion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCursosTotales;
    // End of variables declaration//GEN-END:variables
}
